### PR TITLE
Approved hosts

### LINKED ISSUE #237: [Security] Approved hosts mechanism (GH-227 follow up)
Now that GH-227 has been merged, we need to implement some way of allowing the open in sail button to be injected into third-party GitHub enterprise or GitLab self-hosted instances.

Kyle and I had a meeting to discuss this, and the way we decided on was allowing the button to be injected into any site that appears to be GitHub or GitLab like we used to. When the user clicks on the button, the content script will send the "open in sail" request to the background script which will check the approved hosts list (stored in extension storage as `approved_hosts`). If the host is in the list, the request will be accepted, otherwise a popup will appear asking the user if they want to allow this site to access sail.

This solves the security issue, as any malicious clicks on a sail link would cause a popup to appear (unless the user has trusted that domain already).

The approved hosts list would allow for some sort of wildcard matching (`.example.com` would match `*.example.com` and `example.com`, for example). A configuration page for the extension would be required to remove hosts from the list or manually add them.

We considered storing the approved hosts list in the sail config file (which already exists), but it would be complex for sail to automatically update the approved hosts list if we wanted to add a popup. The extension method seems like a better way (in our opinion) from a UX perspective, and from an ease-of-implementation perspective.

CC: @lucacasonato, @roberthmiller, @kylecarbs

### PR DESCRIPTION
**Pull request by deansheather**
Closes #237.

TODO:
- [x] Add styling to extension config page and popup page
- [x] Test security
- [x] Is it safe to lowercase hostnames?
- [x] Validate the hosts added in the config page
- [x] Make errors more visible to user

### CODE REVIEW

**Comment by roberthmiller** [comment]
As per one of the TODOs, it is safe to lowercase all hosts because uppercase and lowercase values would be routed to the same place. Not really sure if that helps at all.

**Comment by deansheather** [comment]
Screenshot

**Comment by roberthmiller** [comment]
I like the UI for that.

**Comment by deansheather** [comment]
Popup doesn't exist anymore, and the extension "browser action" now opens the config page.

**Comment by deansheather** [comment]
I think this is ready, I've tested that it works on GitHub. I don't think there's any security issues with how it prompts for consent on hosts that aren't already approved (right now the background script injects a confirm dialog into the target tab).

**Pull request merged**
